### ISSUE TITLE
Undefined name 'turn_off_baseline'

### ISSUE THREAD

**Issue by l3str4nge** [EricSteinberger/DREAM#2]
Hey, found undefined name:
`DREAM/DREAM_and_DeepCFR/workers/la/sampling_algorithms/EquityBaselineSampler.py:42:35: F821 undefined name 'turn_off_baseline'`

**Comment by EricSteinberger** [comment]
Hah! Thanks for noting this:) Yeah, we used EquityBaselineSampler for testing and comparison but ditched it in the end because it didn't add value to the paper. Hadn't tested this piece of the code in a while - the components used in the paper should hopefully work though.
